app:
  telegram-token: ${TELEGRAM_TOKEN} # env variable
  scrapper-base-url: http://localhost:8081

spring:
  application:
    name: Bot
  liquibase:
    enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
